import type { Metadata } from 'next';

import Footer from '@/components/footer';
import Header from '@/components/header';
import Main from '@/components/main';

import { geistSans } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Healthy Fox',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}`}>
        <Header />
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}
